version: '3.8'

services:
  frontend:
    container_name: model3d-frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        PUBLIC_PATH: "${FRONTEND_PUBLIC_PATH:-/}"
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    depends_on:
      - backend-api
    restart: unless-stopped
  backend-api:
    container_name: model3d-api
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: go run ./cmd/main.go
    restart: unless-stopped
  postgres:
    container_name: model3d-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_dump/dump.sql:/dump.sql
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    container_name: model3d-redis
    image: redis
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  redis:
    driver: local
  postgres-db:
