version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    image: dengoose/model3d-frontend:latest
  backend-api:
    build: .
    image: dengoose/model3d-backend:latest