version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
  backend-api:
    command: air ./cmd/main.go -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "8095:8095"
    build: .
  postgres:
    ports:
      - "5433:5432"
  redis:
    ports:
      - "6378:6379"