version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8095:8095"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./db_dump/dump.sql:/dump.sql
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6378:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  postgres-db:
