version: '3.8'
# Конфиг для тестового сервера с использованием traefik

services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.model3d.rule=Host(`model3d.serdcebolit.ru`)"
      - "traefik.http.routers.model3d.entrypoints=websecure"
      - "traefik.http.routers.model3d.tls=true"
      - "traefik.http.routers.model3d.tls.certresolver=mainresolver"
      - "traefik.http.services.model3d.loadbalancer.server.port=80"
    networks:
      - internal
      - main_proxy_ivdev_network

  backend-api:
    networks:
      - internal

  postgres:
    networks:
      - internal
  redis:
    networks:
      - internal
networks:
  internal:
    driver: bridge
  main_proxy_ivdev_network:
    external: true