definitions:
  entities.Model:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      model_file:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  entities.PublicUser:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /model/{id}:
    get:
      description: Get model and author by ID model
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Model'
      summary: Get model and author
      tags:
      - Models
  /users:
    get:
      description: Get users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PublicUser'
      summary: Get users
      tags:
      - Users
swagger: "2.0"
