name: Docker Image Builder

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Сборка и пуш образов в Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build backend
        run:
          docker-compose -f docker-compose.build.yml build --parallel
      - name: Push containers
        run:
          docker-compose -f docker-compose.build.yml push